services:
  - type: web
    name: lvup-edu-api
    env: node
    plan: free
    buildCommand: cd apps/api && npm install && npx prisma generate && npm run build
    startCommand: cd apps/api && npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        generateValue: true
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: PORT
        value: 8000
    healthCheckPath: /api/v1
    
  - type: web
    name: lvup-edu-web
    env: node
    plan: free
    buildCommand: cd apps/web && npm install && npm run build
    startCommand: cd apps/web && npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_URL
        fromService:
          type: web
          name: lvup-edu-api
          property: host